### PR TITLE
misc pinned build script fixes - 3.1

### LINKED ISSUE #356: Build script bash path
On a fresh Ubuntu 18.04 install I had to update both install_prereqs.sh and pinned_build.sh to have /bin/bash for the path instead of /usr/bin/bash as they failed to launch

### PR DESCRIPTION
**Pull request by spoonincode**
Resolves #356 but also other issues I've encountered when using the script on all Ubuntu versions: python needs to be installed, and on Ubuntu 18 it's an old cmake so can't use `-S` argument on cmake

### CODE REVIEW

File: scripts/pinned_build.sh [hunk 1]
```diff
@@ -130,7 +130,7 @@ pushdir ${MANDEL_DIR}
 
 # build Mandel
 echo "Building Mandel ${SCRIPT_DIR}"
-try cmake -DCMAKE_TOOLCHAIN_FILE=${SCRIPT_DIR}/pinned_toolchain.cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${LLVM_DIR}/lib/cmake -DCMAKE_PREFIX_PATH=${BOOST_DIR}/bin -S${SCRIPT_DIR}/..
+try cmake -DCMAKE_TOOLCHAIN_FILE=${SCRIPT_DIR}/pinned_toolchain.cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${LLVM_DIR}/lib/cmake -DCMAKE_PREFIX_PATH=${BOOST_DIR}/bin ${SCRIPT_DIR}/..
```
Comment (linh2931) [inline scripts/pinned_build.sh:133]: So will we add -S back after Ubuntu 18.04 retires?

**Review by linh2931 — APPROVED** [review]

File: scripts/pinned_build.sh (hunk 1 above)
Comment (spoonincode) [reply scripts/pinned_build.sh:133]: I'm not sure there is much utility in it how we're using it; it's more interesting when running cmake outside of both the source & build directory.
